version: '3'
services:
  mysql:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - "3306:3306"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    tty: true
  front:
    build:
      context: ./front_end/webpack
    ports:
      - "3000:3000"
    volumes:
      - ./front_end/app/src:/app/src
      - ./front_end/app/public:/app/public
  json_server:
    build:
      context: ./front_end/webpack
    ports:
      - "8000:8000"
    volumes:
      - ./front_end/app/json_server/data.json:/app/json_server/data.json