version: '2'
services:
  webpack:
    build:
      context: ./webpack
    ports:
      - 8080:8080
    container_name: react
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
  json_server:
    build:
      context: ./json_server
    ports:
      - 3000:3000
    container_name: json_server
    volumes:
      - ./app/json_server/data.json:/app/json_server/data.json
